version: '2'

services:
  mysql:
    image: 'mysql:5.6.34'
    ports:
      - '3306:3306'
    env_file:
      - '.env'

  redis:
    image: 'redis:4.0-alpine'
    command: redis-server --requirepass yourpassword
    volumes:
      - 'redis:/data'

  app:
    depends_on:
      - 'mysql'
      - 'redis'
    build: .
    ports:
      - '5000:5000'
    volumes:
      - '.:/app'
    env_file:
      - '.env'

volumes:
  redis:
  mysql: